const ADD_TEMPLATE = 'addTemplate',
      MODIFY_TEMPLATE = 'modifyTemplate',
      DELETE_TEMPLATE = 'delTemplate',
      ADD_INSTANCE = 'addInstance',
      ADD_INSTANCE_ON_TEMPLATE = 'addInstanceOnTemplate',
      DELETE_INSTANCE = 'deleteInstance',
      DELETE_INSTANCE_WHEN_DELETE_TEMPLATE = 'delInstanceWhenDeleteTemplate',
      MODIFY_INSTANCE = 'modifyInstance',
      MODIFY_ITEMS_CUSTOMIZED = 'modifyItemsCustomized',
      CHANGE_STATUS_OF_ITEMS_CUSTOMIZED = 'changeStatusOfItemsCustomized',
      ADD_ITEM = 'addItem',
      ADD_ITEM_WHEN_ADD_TEMPLATE = 'addItemWhenAddTemplate',
      MODIFY_ITEM = 'modifyItem',
      DEL_ITEM = 'delItem',
      DEL_ITEM_MULTI_WHEN_DEL_TEMPLATE = 'delItemWhenDeleteTemplate',
      ADD_ITEMS_CUSTOMIZED = 'addItemsCustomized',
      ADD_ITEMS_CUSTOMIZED_WHEN_ADD_INSTNACE = 'addItemsCustomizedWhenAddInstance',
      DEL_ITEMS_CUSTOMIZED = 'delItemsCustomized',
      ADD_TEMPLATE_CATEGORY = 'addTemplateCategory',
      MODIFY_TEMPLATE_CATEGORY = 'modifyTemplateCategory',
      DEL_TEMPLATE_CATEGORY = 'delTemplateCategory',
      INITIATE_NORMALIZED_DATA_INPUT = 'normalizedDataInput',
      SEARCHBAR_TEXT = 'searchBarText',
      CHOOSE_CATEGORY = 'chooseCategory',
      NAVIGATE_POP_TO_TOP_REQUEST = 'navigatePopToTopRequest',
      FIND_LAST_ID = 'findLastId',
      LAST_ID_PLUS = 'lastIdPlus',
      LAST_ID_PLUS_MULTI = 'lastIdPlusMulti',
      LAST_ID_PLUS_MULTI_OBJECT = 'lastIdPlusMultiObject',
      LAST_ID_PLUS_ONE_BY_ONE = 'lastIdPlusOneByOne',
      LAST_ID_RESKET = 'lastIdReset',
      NAVIGATE_PREVENT = 'navigatePrevent',
      TRIED_NAVIGATE_WHEN_PREVENTED = 'triedNavigateWhenPrevented',
      SAVE_LOCAL = 'savelocal',
      LOAD_LOCAL = 'loadlocal',
      DELETE_ALL = 'deleteAll';

const types = {
  ADD_TEMPLATE,
  MODIFY_TEMPLATE,
  DELETE_TEMPLATE,
  ADD_INSTANCE,
  ADD_INSTANCE_ON_TEMPLATE,
  DELETE_INSTANCE,
  DELETE_INSTANCE_WHEN_DELETE_TEMPLATE,
  MODIFY_INSTANCE,
  MODIFY_ITEMS_CUSTOMIZED,
  CHANGE_STATUS_OF_ITEMS_CUSTOMIZED,
  ADD_ITEM,
  ADD_ITEM_WHEN_ADD_TEMPLATE,
  MODIFY_ITEM,
  DEL_ITEM,
  DEL_ITEM_MULTI_WHEN_DEL_TEMPLATE,
  ADD_ITEMS_CUSTOMIZED,
  ADD_ITEMS_CUSTOMIZED_WHEN_ADD_INSTNACE,
  DEL_ITEMS_CUSTOMIZED,
  ADD_TEMPLATE_CATEGORY,
  MODIFY_TEMPLATE_CATEGORY,
  DEL_TEMPLATE_CATEGORY,
  INITIATE_NORMALIZED_DATA_INPUT,
  SEARCHBAR_TEXT,
  CHOOSE_CATEGORY,
  NAVIGATE_POP_TO_TOP_REQUEST,
  FIND_LAST_ID,
  LAST_ID_PLUS,
  LAST_ID_PLUS_MULTI,
  LAST_ID_PLUS_MULTI_OBJECT,
  LAST_ID_PLUS_ONE_BY_ONE,
  NAVIGATE_PREVENT,
  TRIED_NAVIGATE_WHEN_PREVENTED,
  SAVE_LOCAL,
  LOAD_LOCAL,
  DELETE_ALL
}

export default types
