const ADD_TEMPLATE = 'addNewTemplate',
      MODIFY_TEMPLATE = 'modifyExistingTemplate',
      DELETE_TEMPLATE = 'deleteExistingTemplate',
      ADD_INSTANCE = 'addInstance',
      DELETE_INSTANCE = 'deleteInstance',
      MODIFY_INSTANCE = 'modifyInstance',
      MODIFY_ITEMS_CUSTOMIZED = 'modifyItemsCustomized',
      ADD_ITEM = 'addItem',
      MODIFY_ITEM = 'modifyItem',
      DEL_ITEM = 'delItem',
      ADD_TEMPLATE_CATEGORY = 'addTemplateCategory',
      MODIFY_TEMPLATE_CATEGORY = 'modifyTemplateCategory',
      DEL_TEMPLATE_CATEGORY = 'delTemplateCategory',
      // MY_NORMALIZE = 'my_normalize',
      INITIATE_NORMALIZED_DATA_INPUT = 'normalizedDataInput',
      SEARCHBAR_TEXT_INSTANCE_LIST = 'searchBarTextInstanceList',
      SEARCHBAR_TEXT_ITEMS_OF_CHOSEN_TEMPLATE = 'searchBarTextItemsOfChosenTemplate',
      SEARCHBAR_TEXT_INSTANCES_OF_CHOSEN_TEMPLATE = 'searchBarTextInstancesOfChosenTemplate',
      SEARCHBAR_TEXT_ITEMS_CUSTOMIZED_ALL_INSTANCES = 'searchBarTextItemsCustomizedAllInstances',
      SEARCHBAR_TEXT_TEMPLATE_LIST = 'searchBarTextTemplateList',
      SEARCHBAR_TEXT_ITEM_LIST = 'searchBarTextItemList',
      CHOOSE_CATEGORY = 'chooseCategory';

const types = {
  ADD_TEMPLATE,
  MODIFY_TEMPLATE,
  DELETE_TEMPLATE,
  ADD_INSTANCE,
  DELETE_INSTANCE,
  MODIFY_INSTANCE,
  MODIFY_ITEMS_CUSTOMIZED,
  ADD_ITEM,
  MODIFY_ITEM,
  DEL_ITEM,
  ADD_TEMPLATE_CATEGORY,
  MODIFY_TEMPLATE_CATEGORY,
  DEL_TEMPLATE_CATEGORY,
  // MY_NORMALIZE,
  INITIATE_NORMALIZED_DATA_INPUT,
  SEARCHBAR_TEXT_INSTANCE_LIST,
  SEARCHBAR_TEXT_ITEMS_OF_CHOSEN_TEMPLATE,
  SEARCHBAR_TEXT_INSTANCES_OF_CHOSEN_TEMPLATE,
  SEARCHBAR_TEXT_ITEMS_CUSTOMIZED_ALL_INSTANCES,
  SEARCHBAR_TEXT_TEMPLATE_LIST,
  SEARCHBAR_TEXT_ITEM_LIST,
  CHOOSE_CATEGORY
}

export default types
