const ADD_TEMPLATE = 'addTemplate',
      MODIFY_TEMPLATE = 'modifyTemplate',
      DELETE_TEMPLATE = 'deleteTemplate',
      ADD_INSTANCE = 'addInstance',
      ADD_INSTANCE_THEN_ADD_ON_RESULT = 'addInstanceThenAddOnResult',
      DELETE_INSTANCE = 'deleteInstance',
      MODIFY_INSTANCE = 'modifyInstance',
      MODIFY_ITEMS_CUSTOMIZED = 'modifyItemsCustomized',
      ADD_ITEM = 'addItem',
      MODIFY_ITEM = 'modifyItem',
      DEL_ITEM = 'delItem',
      ADD_ITEMS_CUSTOMIZED = 'addItemsCustomized',
      ADD_TEMPLATE_CATEGORY = 'addTemplateCategory',
      MODIFY_TEMPLATE_CATEGORY = 'modifyTemplateCategory',
      DEL_TEMPLATE_CATEGORY = 'delTemplateCategory',
      INITIATE_NORMALIZED_DATA_INPUT = 'normalizedDataInput',
      SEARCHBAR_TEXT = 'searchBarText',
      CHOOSE_CATEGORY = 'chooseCategory',
      NAVIGATE_POP_TO_TOP_REQUEST = 'navigatePopToTopRequest',
      FIND_LAST_ID = 'findLastId',
      LAST_ID_PLUS = 'lastIdPlus',
      NAVIGATE_PREVENT = 'navigatePrevent',
      TRIED_NAVIGATE_WHEN_PREVENTED = 'triedNavigateWhenPrevented';

const types = {
  ADD_TEMPLATE,
  MODIFY_TEMPLATE,
  DELETE_TEMPLATE,
  ADD_INSTANCE,
  ADD_INSTANCE_THEN_ADD_ON_RESULT,
  DELETE_INSTANCE,
  MODIFY_INSTANCE,
  MODIFY_ITEMS_CUSTOMIZED,
  ADD_ITEM,
  MODIFY_ITEM,
  DEL_ITEM,
  ADD_ITEMS_CUSTOMIZED,
  ADD_TEMPLATE_CATEGORY,
  MODIFY_TEMPLATE_CATEGORY,
  DEL_TEMPLATE_CATEGORY,
  INITIATE_NORMALIZED_DATA_INPUT,
  SEARCHBAR_TEXT,
  CHOOSE_CATEGORY,
  NAVIGATE_POP_TO_TOP_REQUEST,
  FIND_LAST_ID,
  LAST_ID_PLUS,
  NAVIGATE_PREVENT,
  TRIED_NAVIGATE_WHEN_PREVENTED,
}

export default types
